name: 'Setup Foreman'
description: 'Install Foreman, a toolchain manager for Roblox projects'
author: 'The Rojo Developers'
inputs:
  version:
    required: false
    description: 'SemVer version of Foreman to install'
  working-directory:
    required: false
    description: 'Working directory to run `foreman install` in'
  token:
    required: true
    description: 'GitHub token from secrets.GITHUB_TOKEN'
  allow-external-github-orgs:
    required: false
    description: 'Allow installing from external GitHub organizations'
  artifactory-url:
    required: false
    description: 'Artifactory URL to use for downloading Foreman tools'
  artifactory-token:
    required: false
    description: 'Artifactory token to use for downloading Foreman tools'
runs:
  using: 'node16'
  main: 'dist/index.js'
