name: 'Setup Foreman'
description: 'Install Foreman, a toolchain manager for Roblox projects'
author: 'The Rojo Developers'
inputs:
  version:
    description: 'SemVer version of Foreman to install'
  working-directory:
    description: 'Working directory to run `foreman install`` in'
  token:
    description: 'GitHub token from secrets.GITHUB_TOKEN'
runs:
  using: 'node12'
  main: 'dist/index.js'
