# This file is used as a way to make sure that setup-foreman is functioning.

[tools]
rojo = { source = "Roblox/rojo", version = "0.6.0-alpha.1" }
selene = { source = "Roblox/Kampfkarren-selene", version = "0.15.0" }
