# This file is used as a way to make sure that setup-foreman is functioning.

[tools]
selene = { source = "Roblox/tarmac", version = "0.7.0" }
stylua = { source = "Roblox/StyLua", version = "0.13.1" }
