name: "build-test"

on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm run all
    - run: npm run pack

    - uses: ./
      with:
        version: "*"
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: foreman --version
    - run: rojo --version

    - name: Install with working-directory
      uses: ./
      with:
        version: "*"
        token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: tests
    - run: selene --version
