name: "build-test"

on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  build:
    name: Test setup-foreman action
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm run all
    - run: npm run pack

    - name: setup-foreman
      uses: ./
      with:
        version: "*"
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: foreman --version
    - run: rojo --version

  build-in-dir:
    name: Test setup-foreman action with working-directory
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm run all
    - run: npm run pack
    - name: setup-foreman with working-directory
      uses: ./
      with:
        version: "*"
        token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: tests
    - run: foreman --version
    - run: selene --version
    - name: Run installed tool from subfolder
      run: |
        cd tests
        selene --version
